// Copyright (c) 2026 Oliver Kohlbacher and contributors
// SPDX-License-Identifier: MIT
// Statistics + NCBI taxonomy module. Initial implementation generated by the
// kimi CLI from a written spec, then reviewed, numerically verified, and
// integrated (see the species-detector design notes).
//
// TaxStats_test.cpp -- self-contained self-test for the FasTag TaxStats module.
//
// Builds a tiny synthetic NCBI taxonomy (nodes.dmp / names.dmp written into a
// fresh temp directory, including deliberately malformed and duplicate lines),
// then exercises every part of FasTag::Taxonomy with assert-style checks:
// lineage/parent/rank/name, LCA (sister genera -> family, robustness to
// unknown taxids), ancestor-at-rank, subtree-sum rollUp, numerical accuracy
// of binomialUpperTailLogP against a hand-computed case, and end-to-end
// call() behaviour (an enriched genus is flagged with q < 0.05 while a node
// whose observed count matches its expectation is not). Prints
// "TaxStats_test: all checks passed" and returns 0 on success; nonzero on any
// failure. No test framework, no external dependencies.

#include "TaxStats.h"

#include <chrono>
#include <cmath>
#include <cstdint>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <map>
#include <string>
#include <vector>

namespace {

int g_failures = 0;

#define CHECK(cond, msg)                                          \
  do {                                                            \
    if (!(cond)) {                                                \
      std::cerr << "FAIL: " << msg << "  [" #cond "] at line "    \
                << __LINE__ << "\n";                              \
      ++g_failures;                                               \
    }                                                             \
  } while (0)

void writeFile(const std::filesystem::path& p, const std::string& content) {
  std::ofstream out(p);
  out << content;
}

}  // namespace

int main() {
  namespace fs = std::filesystem;

  // --- Synthetic taxonomy -----------------------------------------------
  //   1        root            (no rank)
  //   100      Famidae         (family)      parent 1
  //   110      GenusA          (genus)       parent 100
  //   111      GenusA speciosa (species)     parent 110
  //   112      GenusA minor    (species)     parent 110
  //   120      GenusB          (genus)       parent 100
  //   121      GenusB alpha    (species)     parent 120
  //   200      Otheridae       (family)      parent 1
  //   210      GenusC          (genus)       parent 200
  fs::path dir = fs::temp_directory_path() /
                 ("fastag_taxstats_test_" +
                  std::to_string(std::chrono::steady_clock::now()
                                     .time_since_epoch()
                                     .count()));
  std::error_code ec;
  fs::create_directories(dir, ec);
  if (ec) {
    std::cerr << "cannot create temp dir: " << dir << "\n";
    return 1;
  }
  const fs::path nodes_path = dir / "nodes.dmp";
  const fs::path names_path = dir / "names.dmp";

  writeFile(nodes_path,
            "1\t|\t1\t|\tno rank\t|\t\t|\n"
            "100\t|\t1\t|\tfamily\t|\t\t|\n"
            "110\t|\t100\t|\tgenus\t|\t\t|\n"
            "111\t|\t110\t|\tspecies\t|\t\t|\n"
            "112\t|\t110\t|\tspecies\t|\t\t|\n"
            "120\t|\t100\t|\tgenus\t|\t\t|\n"
            "121\t|\t120\t|\tspecies\t|\t\t|\n"
            "200\t|\t1\t|\tfamily\t|\t\t|\n"
            "210\t|\t200\t|\tgenus\t|\t\t|\n"
            "malformed line without any pipes\n"                 // skipped
            "abc\t|\tdef\t|\tgenus\t|\n"                         // skipped
            "999999999999\t|\t1\t|\tspecies\t|\n"                // skipped (>u32)
            "110\t|\t100\t|\tgenus\t|\t\t|\n");                  // duplicate
  writeFile(names_path,
            "1\t|\troot\t|\t\t|\tscientific name\t|\n"
            "100\t|\tFamidae\t|\t\t|\tscientific name\t|\n"
            "110\t|\tGenusA\t|\t\t|\tscientific name\t|\n"
            "111\t|\tGenusA speciosa\t|\t\t|\tscientific name\t|\n"
            "112\t|\tGenusA minor\t|\t\t|\tscientific name\t|\n"
            "120\t|\tGenusB\t|\t\t|\tscientific name\t|\n"
            "121\t|\tGenusB alpha\t|\t\t|\tscientific name\t|\n"
            "200\t|\tOtheridae\t|\t\t|\tscientific name\t|\n"
            "210\t|\tGenusC\t|\t\t|\tscientific name\t|\n"
            "110\t|\tgenusa-common\t|\t\t|\tcommon name\t|\n"    // ignored
            "777\t|\tGhost\t|\t\t|\tscientific name\t|\n");      // unknown node

  FasTag::Taxonomy tax;
  std::string err;
  CHECK(tax.load(nodes_path.string(), names_path.string(), &err),
        "load() succeeds on synthetic dumps: " + err);
  CHECK(!tax.load(dir.string() + "/nonexistent_nodes.dmp", names_path.string(),
                  nullptr),
        "load() fails cleanly on missing file");

  // --- Tree queries ------------------------------------------------------
  CHECK(tax.known(110), "genus 110 is known");
  CHECK(!tax.known(999), "taxid 999 is unknown");
  CHECK(!tax.known(777), "names-only taxid 777 is not part of the tree");
  CHECK(tax.parent(111) == 110, "parent(111) == 110");
  CHECK(tax.parent(1) == 1, "root is its own parent");
  CHECK(tax.parent(999) == 0, "parent of unknown is 0");
  CHECK(tax.rank(110) == "genus", "rank(110) == genus");
  CHECK(tax.rank(100) == "family", "rank(100) == family");
  CHECK(tax.name(110) == "GenusA", "scientific name of 110 kept");
  CHECK(tax.name(999).empty(), "name of unknown is empty");

  const std::vector<uint32_t> lin = tax.lineage(111);
  CHECK((lin == std::vector<uint32_t>{111, 110, 100, 1}),
        "lineage(111) is species -> genus -> family -> root");
  CHECK(tax.lineage(999).empty(), "lineage of unknown is empty");

  CHECK(tax.lca({110, 120}) == 100, "LCA of sister genera is their family");
  CHECK(tax.lca({111, 121}) == 100, "LCA of species across genera is family");
  CHECK(tax.lca({110, 999999, 120}) == 100,
        "LCA skips unknown taxids and still works");
  CHECK(tax.lca({111, 210}) == 1, "LCA across families is the root");
  CHECK(tax.lca({}) == 0, "LCA of empty set is 0");
  CHECK(tax.lca({999999}) == 0, "LCA of only-unknown set is 0");

  CHECK(tax.ancestorAtRank(111, "genus") == 110, "ancestor of 111 at genus");
  CHECK(tax.ancestorAtRank(111, "family") == 100, "ancestor of 111 at family");
  CHECK(tax.ancestorAtRank(111, "order") == 0, "no ancestor at order");
  CHECK(tax.ancestorAtRank(110, "genus") == 110, "node is its own ancestor");

  // --- Roll-up ------------------------------------------------------------
  const std::vector<std::pair<uint32_t, uint64_t>> hits = {
      {111, 30}, {112, 20}, {121, 5}, {210, 100}, {999, 7} /* unknown */,
      {111, 2} /* duplicate taxid aggregates */};
  const std::vector<FasTag::NodeEvidence> rolled = tax.rollUp(hits);
  std::map<uint32_t, FasTag::NodeEvidence> ev;
  for (const auto& e : rolled) ev[e.taxid] = e;

  bool sorted = true;
  for (size_t i = 1; i < rolled.size(); ++i)
    if (rolled[i - 1].taxid >= rolled[i].taxid) sorted = false;
  CHECK(sorted, "rollUp output is sorted by taxid");
  CHECK(ev.count(999) == 0, "hits at unknown taxids are ignored");
  CHECK(ev[111].direct_hits == 32 && ev[111].subtree_hits == 32,
        "duplicate hits aggregate at the node itself");
  CHECK(ev[110].direct_hits == 0 && ev[110].subtree_hits == 52,
        "genus 110 subtree sum = 32 + 20");
  CHECK(ev[100].subtree_hits == 57, "family 100 subtree sum = 52 + 5");
  CHECK(ev[120].subtree_hits == 5, "genus 120 subtree sum = 5");
  CHECK(ev[210].subtree_hits == 100, "genus 210 subtree sum = 100");
  CHECK(ev[1].subtree_hits == 157, "root subtree sum covers all known hits");

  // --- Binomial upper-tail accuracy ---------------------------------------
  // Hand-computed: P(X >= 8 | n=10, p=0.5) = (45 + 10 + 1) / 1024 = 56/1024.
  const double ref = std::log(56.0 / 1024.0);
  const double got = tax.binomialUpperTailLogP(8, 10, 0.5);
  CHECK(std::fabs(got - ref) < 1e-6,
        "binomialUpperTailLogP(8,10,0.5) matches log(56/1024)");
  CHECK(tax.binomialUpperTailLogP(0, 10, 0.5) == 0.0, "P(X >= 0) == 1");
  CHECK(std::isinf(tax.binomialUpperTailLogP(11, 10, 0.5)) &&
            tax.binomialUpperTailLogP(11, 10, 0.5) < 0,
        "P(X >= k > n) == 0 (-inf log)");
  // Large-n regime: log P(X >= 60 | n=1e6, p=1e-5), lambda = 10. Must be
  // finite, negative, and strongly significant without overflow/underflow.
  const double big = tax.binomialUpperTailLogP(60, 1000000, 1e-5);
  CHECK(std::isfinite(big) && big < -20.0,
        "large-n small-p approximation stays finite and sane");

  // --- Statistical call ----------------------------------------------------
  const uint64_t n_total = 10000;
  const std::vector<std::pair<uint32_t, double>> background_p = {
      {1, 0.02},   {100, 0.006}, {110, 0.001}, {111, 0.0006}, {112, 0.002},
      {120, 0.0006}, {121, 0.0006}, {200, 0.01}, {210, 0.01}};
  const std::vector<FasTag::TaxonCall> calls =
      tax.call(rolled, background_p, n_total, 0.05);

  std::map<uint32_t, FasTag::TaxonCall> by_taxid;
  for (const auto& c : calls) by_taxid[c.taxid] = c;

  // Genus 110: observed 52, expected 10 -> clearly enriched.
  CHECK(by_taxid.count(110) == 1, "enriched genus 110 is called");
  if (by_taxid.count(110)) {
    CHECK(by_taxid[110].qvalue < 0.05, "genus 110 has q < 0.05");
    CHECK(by_taxid[110].rank == "genus" && by_taxid[110].name == "GenusA",
          "rank and name attached to the call");
    CHECK(by_taxid[110].observed == 52 &&
              std::fabs(by_taxid[110].expected - 10.0) < 1e-9,
          "observed/expected reported correctly");
  }
  // Genus 210: observed 100, expected 100 -> at chance, must NOT be called.
  CHECK(by_taxid.count(210) == 0,
        "node with observed == expected is not called");
  // Node 112: observed 20, expected 20 -> also at chance.
  CHECK(by_taxid.count(112) == 0, "second at-chance node is not called");
  // Everything returned must respect the threshold and be q-sorted.
  bool threshold_ok = true, order_ok = true;
  for (size_t i = 0; i < calls.size(); ++i) {
    if (calls[i].qvalue > 0.05) threshold_ok = false;
    if (i > 0 && calls[i - 1].qvalue > calls[i].qvalue) order_ok = false;
  }
  CHECK(threshold_ok, "all returned calls satisfy q <= threshold");
  CHECK(order_ok, "calls sorted by qvalue ascending");

  fs::remove_all(dir, ec);

  if (g_failures != 0) {
    std::cerr << "TaxStats_test: " << g_failures << " check(s) FAILED\n";
    return 1;
  }
  std::cout << "TaxStats_test: all checks passed\n";
  return 0;
}
