// Copyright (c) 2026 Oliver Kohlbacher and contributors
// SPDX-License-Identifier: MIT
// Statistics + NCBI taxonomy module. Initial implementation generated by the
// kimi CLI from a written spec, then reviewed, numerically verified, and
// integrated (see the species-detector design notes).
//
// TaxStats.cpp -- FasTag taxonomy + statistics module (implementation).
//
// Implements FasTag::Taxonomy declared in TaxStats.h: NCBI taxdump parsing
// (tolerant of malformed/duplicate lines), tree queries (lineage, LCA,
// ancestor-at-rank), subtree-sum evidence roll-up, and the per-taxon
// enrichment test. The binomial upper-tail p-value is computed in log space
// with three regimes: exact log-sum-exp summation for n <= 20000; a Poisson
// approximation (lambda = n*p, relative-term summation from k upward) for
// larger n with lambda < 1000, where the binomial is Poisson-like; and a
// normal approximation with continuity correction (erfc, switching to the
// asymptotic Mills-ratio form for z > 30 to avoid underflow) in the remaining
// large-n, moderate-p regime. All state lives in the Taxonomy instance, so
// const methods are safe for concurrent reads after load().

#include "TaxStats.h"

#include <algorithm>
#include <cmath>
#include <cstdlib>
#include <fstream>
#include <limits>
#include <map>
#include <unordered_set>

namespace FasTag {

namespace {

constexpr double kNegInf = -std::numeric_limits<double>::infinity();

// Split a taxdump line on '|' and trim whitespace (tabs/spaces/CR) from each
// field. The trailing "\t|" of well-formed lines yields a final empty field,
// which callers simply ignore via field-count checks.
std::vector<std::string> splitDmpLine(const std::string& line) {
  std::vector<std::string> fields;
  size_t start = 0;
  for (;;) {
    size_t pos = line.find('|', start);
    std::string f = (pos == std::string::npos)
                        ? line.substr(start)
                        : line.substr(start, pos - start);
    size_t b = f.find_first_not_of(" \t\r");
    size_t e = f.find_last_not_of(" \t\r");
    fields.push_back(b == std::string::npos ? std::string() : f.substr(b, e - b + 1));
    if (pos == std::string::npos) break;
    start = pos + 1;
  }
  return fields;
}

bool parseU32(const std::string& s, uint32_t& out) {
  if (s.empty()) return false;
  for (char c : s) {
    if (c < '0' || c > '9') return false;
  }
  unsigned long long v = std::strtoull(s.c_str(), nullptr, 10);
  if (v > 0xFFFFFFFFULL) return false;
  out = static_cast<uint32_t>(v);
  return true;
}

// Log of the standard-normal upper tail Phi_bar(z), stable for large z.
double logNormalUpperTail(double z) {
  if (z <= 30.0) {
    double t = 0.5 * std::erfc(z / std::sqrt(2.0));
    if (t > 0.0) return std::log(t);
  }
  // Asymptotic Mills-ratio expansion: Phi_bar(z) ~ phi(z)/z * (1 - 1/z^2 + 3/z^4).
  double z2 = z * z;
  double corr = 1.0 - 1.0 / z2 + 3.0 / (z2 * z2);
  return -0.5 * z2 - std::log(z) - 0.5 * std::log(2.0 * M_PI) + std::log(corr);
}

}  // namespace

bool Taxonomy::load(const std::string& nodes_dmp, const std::string& names_dmp,
                    std::string* err) {
  std::unordered_map<uint32_t, Node> nodes;

  {
    std::ifstream in(nodes_dmp);
    if (!in) {
      if (err) *err = "cannot open nodes file: " + nodes_dmp;
      return false;
    }
    std::string line;
    while (std::getline(in, line)) {
      if (line.empty()) continue;
      std::vector<std::string> f = splitDmpLine(line);
      if (f.size() < 3) continue;  // malformed: skip
      uint32_t taxid = 0, par = 0;
      if (!parseU32(f[0], taxid) || !parseU32(f[1], par)) continue;
      if (f[2].empty()) continue;
      Node& n = nodes[taxid];  // duplicates: last valid line wins
      n.parent = par;
      n.rank = f[2];
    }
  }
  if (nodes.empty()) {
    if (err) *err = "no valid nodes parsed from: " + nodes_dmp;
    return false;
  }

  {
    std::ifstream in(names_dmp);
    if (!in) {
      if (err) *err = "cannot open names file: " + names_dmp;
      return false;
    }
    std::string line;
    while (std::getline(in, line)) {
      if (line.empty()) continue;
      std::vector<std::string> f = splitDmpLine(line);
      if (f.size() < 4) continue;
      if (f[3] != "scientific name") continue;
      uint32_t taxid = 0;
      if (!parseU32(f[0], taxid)) continue;
      auto it = nodes.find(taxid);
      if (it == nodes.end()) continue;  // name for unknown node: skip
      if (!f[1].empty()) it->second.name = f[1];
    }
  }

  nodes_ = std::move(nodes);
  return true;
}

uint32_t Taxonomy::parent(uint32_t taxid) const {
  auto it = nodes_.find(taxid);
  return it == nodes_.end() ? 0 : it->second.parent;
}

std::string Taxonomy::rank(uint32_t taxid) const {
  auto it = nodes_.find(taxid);
  return it == nodes_.end() ? std::string() : it->second.rank;
}

std::string Taxonomy::name(uint32_t taxid) const {
  auto it = nodes_.find(taxid);
  return it == nodes_.end() ? std::string() : it->second.name;
}

bool Taxonomy::known(uint32_t taxid) const {
  return nodes_.find(taxid) != nodes_.end();
}

std::vector<uint32_t> Taxonomy::lineage(uint32_t taxid) const {
  std::vector<uint32_t> out;
  uint32_t cur = taxid;
  // Cycle-safe: stop at unknown nodes, at a self-parent (root), or when a
  // node repeats. Lineages are shallow (< ~100 levels in NCBI), so the
  // visited set stays tiny.
  std::unordered_set<uint32_t> seen;
  while (cur != 0 && seen.insert(cur).second) {
    auto it = nodes_.find(cur);
    if (it == nodes_.end()) break;
    out.push_back(cur);
    uint32_t par = it->second.parent;
    if (par == cur || par == 0) break;
    cur = par;
  }
  return out;
}

uint32_t Taxonomy::lca(const std::vector<uint32_t>& taxids) const {
  std::vector<std::vector<uint32_t>> lins;
  lins.reserve(taxids.size());
  for (uint32_t t : taxids) {
    if (t == 0 || !known(t)) continue;  // skip unknown
    lins.push_back(lineage(t));
  }
  if (lins.empty()) return 0;

  std::unordered_set<uint32_t> common(lins[0].begin(), lins[0].end());
  for (size_t i = 1; i < lins.size(); ++i) {
    std::unordered_set<uint32_t> s(lins[i].begin(), lins[i].end());
    for (auto it = common.begin(); it != common.end();) {
      if (s.count(*it) == 0) {
        it = common.erase(it);
      } else {
        ++it;
      }
    }
  }
  // lins[0] is ordered leaf -> root, so the first common entry is the lowest.
  for (uint32_t id : lins[0]) {
    if (common.count(id) != 0) return id;
  }
  return 0;
}

uint32_t Taxonomy::ancestorAtRank(uint32_t taxid, const std::string& rank) const {
  for (uint32_t id : lineage(taxid)) {
    if (nodes_.at(id).rank == rank) return id;
  }
  return 0;
}

std::vector<NodeEvidence> Taxonomy::rollUp(
    const std::vector<std::pair<uint32_t, uint64_t>>& hits) const {
  // Aggregate duplicate taxids deterministically (std::map: sorted by taxid).
  std::map<uint32_t, uint64_t> direct;
  for (const auto& h : hits) {
    if (known(h.first)) direct[h.first] += h.second;
  }
  std::map<uint32_t, NodeEvidence> acc;
  for (const auto& kv : direct) {
    for (uint32_t anc : lineage(kv.first)) {
      NodeEvidence& ev = acc[anc];
      ev.taxid = anc;
      ev.subtree_hits += kv.second;
    }
  }
  for (const auto& kv : direct) {
    acc[kv.first].direct_hits += kv.second;
  }
  std::vector<NodeEvidence> out;
  out.reserve(acc.size());
  for (const auto& kv : acc) out.push_back(kv.second);
  return out;
}

double Taxonomy::binomialUpperTailLogP(uint64_t k, uint64_t n, double p) const {
  if (k == 0) return 0.0;               // P(X >= 0) == 1
  if (k > n) return kNegInf;            // impossible
  if (p <= 0.0) return kNegInf;         // P(X >= k > 0) == 0 when p == 0
  if (p >= 1.0) return 0.0;             // X == n >= k with probability 1

  if (n <= kExactMaxN) {
    // Exact: sum_{i=k}^n C(n,i) p^i (1-p)^(n-i) via log-sum-exp.
    const double lp = std::log(p);
    const double lq = std::log1p(-p);
    const double ln_fact = std::lgamma(static_cast<double>(n) + 1.0);
    double maxlog = kNegInf;
    for (uint64_t i = k; i <= n; ++i) {
      double t = ln_fact - std::lgamma(static_cast<double>(i) + 1.0) -
                 std::lgamma(static_cast<double>(n - i) + 1.0) +
                 static_cast<double>(i) * lp +
                 static_cast<double>(n - i) * lq;
      if (t > maxlog) maxlog = t;
    }
    double sum = 0.0;
    for (uint64_t i = k; i <= n; ++i) {
      double t = ln_fact - std::lgamma(static_cast<double>(i) + 1.0) -
                 std::lgamma(static_cast<double>(n - i) + 1.0) +
                 static_cast<double>(i) * lp +
                 static_cast<double>(n - i) * lq;
      sum += std::exp(t - maxlog);
    }
    return maxlog + std::log(sum);
  }

  const double lambda = static_cast<double>(n) * p;
  if (lambda < kPoissonMaxLambda) {
    // Poisson approximation (valid for large n, small p): P(X >= k) with
    // X ~ Poisson(n*p). Sum relative terms from i = k upward; the ratio
    // t_{i+1}/t_i = lambda/(i+1) makes the recursion stable. Terminates once
    // terms are negligible relative to the accumulated sum.
    double logterm_k = -lambda + static_cast<double>(k) * std::log(lambda) -
                       std::lgamma(static_cast<double>(k) + 1.0);
    double rel = 1.0;   // term_i / term_k
    double sum = 1.0;   // sum of relative terms
    for (uint64_t i = k;; ++i) {
      rel *= lambda / static_cast<double>(i + 1);
      if (rel < 1e-17 * sum && static_cast<double>(i + 1) > lambda) break;
      sum += rel;
    }
    return logterm_k + std::log(sum);
  }

  // Normal approximation with continuity correction (large n, moderate p).
  const double mu = lambda;
  const double var = static_cast<double>(n) * p * (1.0 - p);
  const double z = (static_cast<double>(k) - 0.5 - mu) / std::sqrt(var);
  return logNormalUpperTail(z);
}

std::vector<TaxonCall> Taxonomy::call(
    const std::vector<NodeEvidence>& rolled,
    const std::vector<std::pair<uint32_t, double>>& background_p,
    uint64_t n_total, double q_threshold) const {
  std::unordered_map<uint32_t, double> pmap;
  pmap.reserve(background_p.size());
  for (const auto& bp : background_p) pmap[bp.first] = bp.second;

  struct Tested {
    uint32_t taxid;
    uint64_t observed;
    double expected;
    double logp;
    double q;
  };
  std::vector<Tested> tested;
  for (const NodeEvidence& ev : rolled) {
    if (ev.subtree_hits < kObservedFloor) continue;
    auto it = pmap.find(ev.taxid);
    if (it == pmap.end()) continue;
    double p = it->second;
    if (!(p >= 0.0) || p > 1.0) continue;  // NaN or invalid: skip
    Tested t;
    t.taxid = ev.taxid;
    t.observed = ev.subtree_hits;
    t.expected = static_cast<double>(n_total) * p;
    t.logp = binomialUpperTailLogP(ev.subtree_hits, n_total, p);
    t.q = 1.0;
    tested.push_back(t);
  }

  // Benjamini-Hochberg: sort by p-value ascending (log space), then
  // q_(i) = min_{j>=i} p_(j) * m / j, enforced monotonic from the largest p.
  std::sort(tested.begin(), tested.end(), [](const Tested& a, const Tested& b) {
    if (a.logp != b.logp) return a.logp < b.logp;
    return a.taxid < b.taxid;
  });
  const double m = static_cast<double>(tested.size());
  double best = 1.0;
  for (size_t i = tested.size(); i-- > 0;) {
    double pv = std::exp(tested[i].logp);  // underflows to 0 for tiny p: fine
    double qv = pv * m / static_cast<double>(i + 1);
    if (qv < best) best = qv;
    tested[i].q = best;
  }

  std::vector<TaxonCall> out;
  for (const Tested& t : tested) {
    if (t.q > q_threshold) continue;
    TaxonCall c;
    c.taxid = t.taxid;
    c.rank = rank(t.taxid);
    c.name = name(t.taxid);
    c.observed = t.observed;
    c.expected = t.expected;
    c.log_pvalue = t.logp;
    c.qvalue = t.q;
    out.push_back(c);
  }
  std::sort(out.begin(), out.end(), [](const TaxonCall& a, const TaxonCall& b) {
    if (a.qvalue != b.qvalue) return a.qvalue < b.qvalue;
    if (a.observed != b.observed) return a.observed > b.observed;
    return a.taxid < b.taxid;
  });
  return out;
}

}  // namespace FasTag
