// Copyright (c) 2026 Oliver Kohlbacher and contributors
// SPDX-License-Identifier: MIT
// Statistics + NCBI taxonomy module. Initial implementation generated by the
// kimi CLI from a written spec, then reviewed, numerically verified, and
// integrated (see the species-detector design notes).
//
// TaxStats.h -- FasTag taxonomy + statistics module (interface).
//
// This header declares FasTag::Taxonomy, a self-contained C++17 module that
// (1) loads the NCBI taxonomy tree from nodes.dmp / names.dmp dumps and
// answers tree queries (parent, rank, name, lineage, LCA, ancestor-at-rank),
// (2) rolls per-taxon observed hit counts up the tree into subtree sums, and
// (3) performs a per-taxon enrichment test: a numerically stable log-space
// binomial upper-tail p-value per node, corrected across all tested nodes
// with Benjamini-Hochberg. It depends only on the standard library, holds no
// global mutable state, and is thread-safe for concurrent const reads after
// load() completes. It knows nothing about spectra, tags, or k-mers.

#pragma once

#include <cstdint>
#include <string>
#include <unordered_map>
#include <utility>
#include <vector>

namespace FasTag {

// Evidence accumulated at one taxonomy node: hits observed directly at the
// node, and the sum over the node's whole subtree (itself + all descendants).
struct NodeEvidence {
  uint32_t taxid = 0;
  uint64_t direct_hits = 0;
  uint64_t subtree_hits = 0;
};

// Result of the statistical call for one taxon that passed the q-value
// threshold. log_pvalue is the natural log of the raw binomial upper-tail
// p-value; qvalue is the Benjamini-Hochberg adjusted value in [0,1].
struct TaxonCall {
  uint32_t taxid = 0;
  std::string rank;
  std::string name;
  uint64_t observed = 0;
  double expected = 0.0;
  double log_pvalue = 0.0;
  double qvalue = 1.0;
};

class Taxonomy {
public:
  // Load NCBI taxdump files. nodes.dmp fields: taxid | parent_taxid | rank | ...
  // names.dmp fields: taxid | name_txt | unique_name | name_class |; only rows
  // with name_class == "scientific name" are kept. Malformed or duplicate
  // lines are skipped without failing. Returns false (and sets *err when
  // given) only if a file cannot be opened or yields zero valid nodes.
  bool load(const std::string& nodes_dmp, const std::string& names_dmp,
            std::string* err);

  // Parent taxid. Returns 0 for unknown taxids; the root (taxid 1) has itself
  // as parent, mirroring the NCBI dump.
  uint32_t parent(uint32_t taxid) const;

  // Rank string ("genus", "family", "species", ...), empty if unknown.
  std::string rank(uint32_t taxid) const;

  // Scientific name, empty if unknown.
  std::string name(uint32_t taxid) const;

  // True if the taxid appears in the loaded tree.
  bool known(uint32_t taxid) const;

  // Path from taxid up to (and including) the root; empty if unknown.
  std::vector<uint32_t> lineage(uint32_t taxid) const;

  // Lowest common ancestor of the given taxids. Unknown taxids are skipped;
  // returns 0 if no known taxid remains.
  uint32_t lca(const std::vector<uint32_t>& taxids) const;

  // Nearest ancestor (including taxid itself) having the given rank; 0 if none.
  uint32_t ancestorAtRank(uint32_t taxid, const std::string& rank) const;

  // Roll observed (taxid, count) hits up the tree. For every node that is an
  // ancestor of (or equal to) an observed taxid, produce its subtree sum.
  // O(hits * average lineage depth); output sorted ascending by taxid.
  // Hits at unknown taxids are ignored.
  std::vector<NodeEvidence> rollUp(
      const std::vector<std::pair<uint32_t, uint64_t>>& hits) const;

  // Natural log of P(X >= k) for X ~ Binomial(n, p).
  // Regimes (documented in the .cpp):
  //   n <= kExactMaxN:          exact summation in log space (log-sum-exp).
  //   n large, n*p < kPoissonMaxLambda: Poisson approximation, log space.
  //   otherwise:                normal approximation with continuity
  //                             correction, erfc-based with asymptotic tail.
  double binomialUpperTailLogP(uint64_t k, uint64_t n, double p) const;

  // Statistical call. For every rolled node with subtree_hits >= kObservedFloor
  // and a supplied background probability p_T, compute expected = n_total*p_T
  // and log_pvalue = binomialUpperTailLogP(subtree_hits, n_total, p_T), then
  // apply Benjamini-Hochberg across all tested nodes. Returns the nodes with
  // qvalue <= q_threshold, sorted by qvalue ascending, then observed
  // descending (ties broken by taxid for determinism). Rank and name are
  // attached from the taxonomy. Nodes without a background_p entry are not
  // tested.
  std::vector<TaxonCall> call(
      const std::vector<NodeEvidence>& rolled,
      const std::vector<std::pair<uint32_t, double>>& background_p,
      uint64_t n_total, double q_threshold) const;

  // Minimum subtree_hits for a node to enter the multiple-testing pool.
  static constexpr uint64_t kObservedFloor = 5;

private:
  struct Node {
    uint32_t parent = 0;
    std::string rank;
    std::string name;
  };
  std::unordered_map<uint32_t, Node> nodes_;

  // Regime thresholds for binomialUpperTailLogP.
  static constexpr uint64_t kExactMaxN = 20000;
  static constexpr double kPoissonMaxLambda = 1000.0;
};

}  // namespace FasTag
